// // на всякий для моковых данных
// import type { Therapist } from './types';

// export const mockDoctors: Therapist[] = [
//   {
//     id: '1',
//     first_name: 'Иван',
//     middle_name: 'П.',
//     last_name: 'Петров',
//     photo: '/images/doctor1.jpg',
//     phone_number: '123456789',
//     email: 'ivan@mail.com',
//     password: '123',
//     education: 'МГУ, психология',
//     experience: '5',
//     qualification: 'Гештальт психолог, терапевт',
//     consult_areas: 'Тревога • Депрессия • Самооценка',
//     short_description: 'Помогаю справляться с тревогой и депрессией',
//     description: 'Опыт работы более 5 лет с разными клиентами',
//     office: 'Москва'
//   },
//   {
//     id: '2',
//     first_name: 'Мария',
//     middle_name: 'И.',
//     last_name: 'Иванова',
//     photo: '/images/doctor2.jpg',
//     phone_number: '123456789',
//     email: 'maria@mail.com',
//     password: '123',
//     education: 'СПбГУ, психология',
//     experience: '8',
//     qualification: 'Клинический психолог',
//     consult_areas: 'Отношения • Выгорание • Самооценка',
//     short_description: 'Работаю с личными и профессиональными кризисами',
//     description: 'Опыт работы 8 лет, веду индивидуальные и групповые сессии',
//     office: 'Санкт-Петербург'
//   },
//     {
//     id: '1',
//     first_name: 'Иван',
//     middle_name: 'П.',
//     last_name: 'Петров',
//     photo: '/images/doctor1.jpg',
//     phone_number: '123456789',
//     email: 'ivan@mail.com',
//     password: '123',
//     education: 'МГУ, психология',
//     experience: '5',
//     qualification: 'Гештальт психолог, терапевт',
//     consult_areas: 'Тревога • Депрессия • Самооценка',
//     short_description: 'Помогаю справляться с тревогой и депрессией',
//     description: 'Опыт работы более 5 лет с разными клиентами',
//     office: 'Москва'
//   },
//   {
//     id: '2',
//     first_name: 'Мария',
//     middle_name: 'И.',
//     last_name: 'Иванова',
//     photo: '/images/doctor2.jpg',
//     phone_number: '123456789',
//     email: 'maria@mail.com',
//     password: '123',
//     education: 'СПбГУ, психология',
//     experience: '8',
//     qualification: 'Клинический психолог',
//     consult_areas: 'Отношения • Выгорание • Самооценка',
//     short_description: 'Работаю с личными и профессиональными кризисами',
//     description: 'Опыт работы 8 лет, веду индивидуальные и групповые сессии',
//     office: 'Санкт-Петербург'
//   },
//     {
//     id: '1',
//     first_name: 'Иван',
//     middle_name: 'П.',
//     last_name: 'Петров',
//     photo: '/images/doctor1.jpg',
//     phone_number: '123456789',
//     email: 'ivan@mail.com',
//     password: '123',
//     education: 'МГУ, психология',
//     experience: '5',
//     qualification: 'Гештальт психолог, терапевт',
//     consult_areas: 'Тревога • Депрессия • Самооценка',
//     short_description: 'Помогаю справляться с тревогой и депрессией',
//     description: 'Опыт работы более 5 лет с разными клиентами',
//     office: 'Москва'
//   },
//   {
//     id: '2',
//     first_name: 'Мария',
//     middle_name: 'И.',
//     last_name: 'Иванова',
//     photo: '/images/doctor2.jpg',
//     phone_number: '123456789',
//     email: 'maria@mail.com',
//     password: '123',
//     education: 'СПбГУ, психология',
//     experience: '8',
//     qualification: 'Клинический психолог',
//     consult_areas: 'Отношения • Выгорание • Самооценка',
//     short_description: 'Работаю с личными и профессиональными кризисами',
//     description: 'Опыт работы 8 лет, веду индивидуальные и групповые сессии',
//     office: 'Санкт-Петербург'
//   },

// ];
